### ISSUE TITLE
Will this package have a similar experience like swiper?

### ISSUE THREAD

**Issue by AmaiKinono** [raxod502/ctrlf#11]
I'm migrating from ivy to selectrum (as you know). Now what I miss most is swiper and `counsel-git-grep`. I can do search & replace with the built in tools from Emacs, but when I'm just searching and jumping to places (without replace), I would like to have an ivy/selectrum like UI. When I was just thinking about implementing it using selectrum, I saw this package. I haven't tried it mainly because I didn't get an impression from the README. So, what will it be like? Could you talk a little about your blueprint or design?

**Comment by raxod502** [comment]
No. My motivation for creating CTRLF was to replace Swiper, but I wanted to consider carefully what would be the best interface rather than simply re-creating what already existed. On reflection, I decided that the best interface would be a version of Isearch that fixes its idiosyncrasies, rather than something based on Selectrum. This is because I realized that I never actually looked at the matches shown in the minibuffer, because they lacked enough context. The only information I actually got from the minibuffer was the number of matches and my relative position within them. So why not go for a more streamlined approach based on the Isearch paradigm, with a count and index reported in the minibuffer?

The design is based on the function of the ctrl-F binding in most programs, since this has been well-established as an effective and intuitive interface for text search. However, the bindings are remapped from Isearch for consistency with Emacs.

My main goal for development is to reduce the fragility of the Isearch interface; you should only exit a search by intentional keystroke. Also, wraparound should be automatic and information about wraparound should be communicated to the user by means of the index and match count indicator.

I would advise trying the package. It does not require setup beyond `straight-use-package` and `M-x ctrlf-mode`. Then you can see what you think.

**Comment by AmaiKinono** [comment]
> This is because I realized that I never actually looked at the matches shown in the minibuffer, because they lacked enough context.

You are right. I rethought why I prefer swiper over isearch, and found it's not because I can do filtering in the minibuffer, but various small things:

- It feels easy to break an isearch session.
- Swiper highlights the whole line, so I know where I am immediately.
- I can type `M-n` to input the symbol under point.
- The regex builder.
- I can do grep using commands like `counsel-git-grep`, and it has a similar experience.

About the regex builder: I think it is both convenient and confusing:

- When I want to quickly search and jump to a line, for example where `some-symbol` is defined (without knowing if it's a function/symbol/etc..), I would search for `def some-symbol`. It feels convenient.

- When I want to do a regexp search & replace, sometimes it feels not easy to look at the input, guess what the regexp built by ivy is, and write the regexp for replacing (especially with group related stuff). It's better to use regexp to search & replace directly. Though I need to type more this way, it feels better on the mental side.

So I think maybe ctrlf can do some basic regex rebuild thing in regexp search commands. Just translating a single space into `.*`, and n spaces into n-1 is good enough.

About grep: Seems ctrlf focuses on single buffer search, but I'll just say some of my thoughts. When I'm just grepping and jumping to places, I really don't like bringing in another `grep` buffer. I think the UI of ctrlf can be slightly modified to do grepping: Show the matched files in minibuffer (maybe horizontally), and add 2 commands to jump between files. When a file is selected, it's still like single buffer searching. I guess this may be some huge amount of works, and of course, it's up to you to whether do it or not.

**Comment by raxod502** [comment]
> It feels easy to break an isearch session.

Yes, and I intended to solve that problem with the CTRLF implementation.

> Swiper highlights the whole line, so I know where I am immediately.

I would be fine with this being added as a user option.

> I can type M-n to input the symbol under point.

I don't know if we want this keybinding by default (after all, Isearch provides similar functionality under a different binding), but that is a good feature to add.

> The regex builder.

I guess I would be fine with adding this as an option, as long as it supports arbitrary regexps correctly unlike Ivy. Not enabled by default.

> About grep

This seems mostly out of scope, but perhaps I could be convinced by a sufficiently elegant implementation. I would definitely be fine with this functionality being implemented in a third package using both CTRLF and Selectrum simultaneously, and the necessary hooks/options being added to both dependencies.

**Comment by AmaiKinono** [comment]
I think we can close this issue for now, since most things mentioned were implemented, except the grep thing, which may not happen at least in the near future.
