### ISSUE TITLE
first character is not deleted

### ISSUE THREAD

**Issue by gintering1000** [raxod502/ctrlf#111]
![Screen Capture 2022-02-03 at 19 03 29](https://user-images.githubusercontent.com/77244047/152321928-3a293ced-2122-41d7-a98e-0a88e0d36f97.gif)

first character is not deleted.

it show when i set (menu-bar-mode -1)

**Comment by raxod502** [comment]
Hmm, interesting, unfortunately to investigate I think I would need more information about your system configuration, since I also have `menu-bar-mode` disabled yet don't experience this behavior. Can you reproduce the issue from `emacs -Q` or is it the result of something else in your Emacs configuration in concert with CTRLF?

**Comment by gintering1000** [comment]
sorry. i dont know how to install package in [ -Q mode ].

![image](https://user-images.githubusercontent.com/77244047/152660260-1334477f-2d7f-44ba-acdc-7b1f83af2696.png)
![Screen Capture 2022-02-06 at 06 51 51](https://user-images.githubusercontent.com/77244047/152660234-ce287d7d-9893-4b6c-a4b9-d8ffdca393b5.gif)
![image](https://user-images.githubusercontent.com/77244047/152660239-d70b8141-1a68-4003-b2ad-f6369ff70048.png)
![image](https://user-images.githubusercontent.com/77244047/152660246-7ab7d573-2b8a-4439-b6b6-f8824409ad15.png)
![image](https://user-images.githubusercontent.com/77244047/152660323-9dd4506f-53a6-4862-8fe2-1698e4ad5b6d.png)
![image](https://user-images.githubusercontent.com/77244047/152660286-289195fe-d154-41a5-ba3d-a979b9dd13a5.png)
![image](https://user-images.githubusercontent.com/77244047/152660302-011cefd3-0dab-4afc-b9a4-aaab0c41cd25.png)
![image](https://user-images.githubusercontent.com/77244047/152660554-b21697a2-fc0a-41da-9eec-432851940db1.png)


```
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; PLUGIN MANAGER
(defvar bootstrap-version)
(let ((bootstrap-file
  (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
  (bootstrap-version 5))
(unless (file-exists-p bootstrap-file)
  (with-current-buffer
    (url-retrieve-synchronously
      "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
      'silent 'inhibit-cookies)
  (goto-char (point-max))
  (eval-print-last-sexp)))
(load bootstrap-file nil 'nomessage))
(straight-use-package 'el-patch)
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; PACKAGE
(use-package ctrlf :config (ctrlf-mode t) )
```
reproducing process
- brew tap daviderestivo/emacs-head
- brew install emacs@28
- delete all .emacs.d directory in home path
- make .emacs file with below config
- execute emacs ( emacs -nw )
- this is all i did

i chekced again.. it is not because of menubar

**Comment by raxod502** [comment]
Thanks, this is helpful. One more thing, can you show the contents of the lossage buffer after starting Emacs and reproducing the issue? (Type `C-h l` and it shows a log of the last 200 keystrokes as well as the commands they triggered.)

**Comment by gintering1000** [comment]
![image](https://user-images.githubusercontent.com/77244047/152660991-3a549ddf-90fd-4dc4-aee3-851d31b25a6f.png)
![Screen Capture 2022-02-06 at 07 26 32](https://user-images.githubusercontent.com/77244047/152661045-a2d58dc2-6785-4370-89a1-65ca26cbcb03.gif)
![Screen Capture 2022-02-06 at 07 26 48](https://user-images.githubusercontent.com/77244047/152661047-165ac28e-53dc-47fc-90d3-1479b6352345.gif)

**Comment by gintering1000** [comment]
![Screen Capture 2022-02-06 at 07 43 16](https://user-images.githubusercontent.com/77244047/152661407-8b6bf1a0-3deb-4633-9b7e-a192f18d0763.gif)
![image](https://user-images.githubusercontent.com/77244047/152661429-06a49628-e406-4422-ab4d-df21ee520bba.png)

i think this is what you want
( maybe korean ( ko_kr ) problem right? )

so many time. i experience korean language problem from other app.. like this.
for example.
![Screen Capture 2022-02-06 at 07 55 55](https://user-images.githubusercontent.com/77244047/152661686-aa2dbcb8-d290-4429-8888-de00a3ff1724.gif)
 after write down korean ( = 안녕 ), i press two enter. but newline is one.

**Comment by raxod502** [comment]
I see you closed the issue, so maybe you worked it out on your own? But if not, it would really be much more helpful to see the lossage output in text format rather than a screenshot, and to see which section specifically corresponds to the actions you're performing in the screencapture; it's really hard to untangle everything right now, so I can't really tell what keys are actually being pressed.

**Comment by gintering1000** [comment]
it didnt work~. i just closed cuz you didnt answer me~ sorry. i will open it again if you want.

and i will help you if you want something~ i can do what you want.

but i dont know how can i reopen this :)

**Comment by raxod502** [comment]
> i just closed cuz you didnt answer me

I do open-source maintenance in my free time, for free, so I don't generally get back to questions every single day. At most it's a few times a week.

> i dont know how can i reopen this

You might not have permission to reopen. I reopened the issue for you.

> and i will help you if you want something

Well, as I mentioned above, what I'd need is---the lossage output in text format rather than a screenshot, and to see which section specifically corresponds to the actions you're performing in the screencapture.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/radian-software/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)
