### ISSUE TITLE
C-r wrong

### ISSUE THREAD

**Issue by Yeahowhen** [raxod502/ctrlf#116]
when i use C-r to search something in reverse and i use C-r for the next one then it shows Next element matching (regex) in minibuffer.

Note: I have helm in emacs and i don't know if there is something relatively.

**Comment by raxod502** [comment]
Probably an issue with keybinding precedence. Similar problems have been reported in the past with https://github.com/radian-software/ctrlf/issues/51.

When I install Helm and activate it with `M-x helm-mode` I do not observe any different behavior from CTRLF. Can you provide instructions for how to reproduce the error you're seeing?

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/radian-software/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)
