### ISSUE TITLE
Keep current match in the middle of the window?

### ISSUE THREAD

**Issue by AmaiKinono** [raxod502/ctrlf#12]
Sometimes we are just searching to peek things. When the match is on the beginning/end of the window, we have to search backward/forward again and then move back to show its surroundings. So how about keeping current match in the middle of the window?

**Comment by raxod502** [comment]
That seems disorienting as a default behavior; what about just allowing you to type `C-l` to recenter, as proposed in #7?

**Comment by AmaiKinono** [comment]
> That seems disorienting as a default behavior

Actually I don't see why, but having a recenter command would be good enough. If I want automatic recenter anyway I can wrap my own commands for it.

**Comment by raxod502** [comment]
> I don't see why

Because it prevents the user from tracking other visual landmarks in the buffer. Observe that when you do a text search in a web browser, for example, the screen is not scrolled unless it needs to me. This makes it easier to maintain your place in reading.

> I can wrap my own commands for it

Yes, I think that would be easy. I would not be opposed to adding an option to do this by default.
