### ISSUE TITLE
Point is not reset correctly in some circumstances

### ISSUE THREAD

**Issue by raxod502** [raxod502/ctrlf#6]
I do not currently have a full recipe to reproduce this issue, but sometimes pressing `C-g` will not reset point to its original position, but rather to the beginning of the current line.

**Comment by AmaiKinono** [comment]
This happens to me whenever the initial point position is not in the displayed part before `C-g`. I think it's because Emacs never let the point go outside of the window.

**Comment by raxod502** [comment]
I tested that and you seem to be right. Thanks!

**Comment by AmaiKinono** [comment]
Here's another problem. It's a corner case, kinda hard to describe, but due to the same reason. See this:

![ctrlf-not-correct-after-search](https://user-images.githubusercontent.com/28714352/73643453-7fc39780-46ae-11ea-9e4f-8c477aaf23e0.gif)

I search for `parse`, and it's near the lower boundary of the window. Press `RET` to jump to it, and since `CTRLF` finishes its search, `awesome-tray` pops a 2-line information, and `parse` is outside of the window again, and the point goes to the center (I highlighted it so you can see more clearly).

**Comment by raxod502** [comment]
Oh, that's unfortunate. Thanks for the report.

**Comment by raxod502** [comment]
I believe the issue I reported is fixed. Can you let me know if your issue is solved as well, or if it is still a problem?

**Comment by AmaiKinono** [comment]
The problem is still there with awesome-tray, but I've switched to mini-modeline(https://github.com/kiennq/emacs-mini-modeline) and it won't take more than 1 lines, so it's no longer a problem for me.

**Comment by raxod502** [comment]
Okay. The multiline modeline configuration seems like an uncommon one to me, so let's close this as an edge case. If somebody else comes along with the issue, we can take another look.
