### ISSUE TITLE
Make minibuffer keymap available

### ISSUE THREAD

**Issue by rgrinberg** [raxod502/ctrlf#62]
Hi,

I like using [which-key](https://github.com/justbur/emacs-which-key/) to inspect keymaps. Is there a reason why the keymap itself has to be created on the fly? Can it be the global variable we get to customize instead of the list of bindings.

**Comment by raxod502** [comment]
It's because I thought it was an elegant idea at the time. Since then, it has been pointed out by everyone else on the Internet that it's not a good idea -- but nobody has yet gone back and changed the variable to a regular keymap :)

**Comment by rgrinberg** [comment]
I can send a PR if you agree that this is a good change. Do you think we can keep compat with the old variable? Or should we just delete it and replace it with a new map variable.

**Comment by raxod502** [comment]
Yes, definitely a good change, feel free. I'd _like_ to keep backwards compatibility, but it's a little tricky in this case. Here's one way that I think could work nicely. When we are applying the keymap, we can check the value of `ctrlf-mode-bindings` against its default value (this is stored in the `standard-value` symbol property) to see if it's been customized. If so, we could use that instead of the new keymap variable, possibly printing a warning in the process.

**Comment by hrehfeld** [comment]
Awesome, thanks for the PR, but I have a few questions:

- why is ctrlf-mode-bindings still present? (backwards-compat?)
- why is there no map for minibuffer-bindings? (oh, I see the title now)
- documentation in readme is outdated and doesn't mention the map.

**Comment by raxod502** [comment]
> why is ctrlf-mode-bindings still present? (backwards-compat?)

Yes, backwards compatibility.

> why is there no map for minibuffer-bindings? (oh, I see the title now)

Looks like only one of the two keymaps was fixed in the linked PR, I didn't notice that before.

> documentation in readme is outdated and doesn't mention the map

It's been updated in the linked PR.

**Comment by raxod502** [comment]
Thanks to @dawranliou this has now been fixed in https://github.com/raxod502/ctrlf/pull/97.
