### ISSUE TITLE
ctrlf-fuzzy: ignore the order of words

### ISSUE THREAD

**Issue by irigone** [raxod502/ctrlf#70]
When searching for the `ctrlf-minibuffer-post-command-hook` function in the source code, I didn't know the exact function name, so I used consult-line 
(swiper but without ivy as a dependency) anddsearched for "command minib". consult-line shows the line. ctrlf-fuzzy-forward does not. IMO ctrlf-fuzzy should ignore the order of words to be fuzzier

**Comment by raxod502** [comment]
It's a little tricky to do that since we would have to generalize CTRLF to allow search queries that cannot be expressed as a single regexp. I am somewhat reluctant to do that. It makes sense in the context of `consult-line` since that command inherently operates on lines, but CTRLF does not operate on lines; it operates (like Isearch) directly on the character stream of the buffer. There can be more than one search result on the same line, and matches can themselves be multiline. I am not sure how the concept of out-of-order matching could reasonably be extended to this paradigm.
