### ISSUE TITLE
integration with embark

### ISSUE THREAD

**Issue by rileyrg** [raxod502/ctrlf#75]
I like it a lot but invoking embark eg to save a result set using embark-export doesn't work (results in empty export). Is this something that is easily addressed or am I flogging a dead horse?

post edit : Ah, I see ctrlf-occur. That answers 99% of my issue but I guess the "Bigger" issue of embark interaction remains.

**Comment by raxod502** [comment]
I am guessing the reason this does not work is because CTRLF is not based on `completing-read` (or, indeed, any completions interface or package). Although you might be fooled by the UI, the fundamental operation is actually just `search-forward` / `search-backward`, and the match count and index are computed after the fact in a separate step. Whereas for other packages such as consult-line, a full list of candidates is generated explicitly, which can then be exported to Embark.
